// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContinue': string;
  'buttonLink': string;
  'buttonLinkSpan': string;
  'descriptionTitle': string;
  'iconArrowLeft': string;
  'linkToSing': string;
  'linkToSingUpAll': string;
  'modal': string;
  'modalBackground': string;
  'paper': string;
  'questionSingIn': string;
  'textButton': string;
}
export const cssExports: CssExports;
export default cssExports;
